In [ ]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
'''
NumPy is a foundational library for scientific computing and data analysis in Python, providing support for multi-dimensional arrays and efficient numerical operations.

Purpose of NumPy
Efficient Numerical Computation: Handles large datasets quickly with optimized performance.
Facilitates Scientific Computing: Provides tools for complex mathematical and statistical operations.
Performance Improvement: Faster than Python’s built-in lists due to its implementation in C.
Advantages of NumPy
Efficient Storage and Speed: Uses less memory and performs faster operations compared to Python lists.
Vectorized Operations: Enables fast, batch computations without explicit loops.
Comprehensive Functions: Offers a wide range of mathematical, statistical, and linear algebra functions.
Compatibility: Serves as the foundation for many other libraries like pandas, SciPy, and scikit-learn.
Data Manipulation: Ideal for data analysis, machine learning, and data preprocessing tasks.
Enhancing Python’s Capabilities
Improves Execution Speed: Optimizes numerical computations with specialized data structures.
Supports Broadcasting: Allows operations on arrays of different shapes.
Integrates with Accelerators: Works with GPUs for parallel processing.
Conclusion: NumPy significantly enhances Python’s numerical computing capabilities, making it essential for data science, machine learning, and other scientific applications.
'''

# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# In NumPy, both np.mean() and np.average() functions are used to compute the mean (average) of an array, but they have some key differences in terms of functionality and usage.
# >> Comparison of np.mean() and np.average()
'''
>> np.mean()
* Computes the arithmetic mean of an array.
* Does not support weights.
* a, axis, dtype, out, keepdims.
* Averages all elements along the specified axis or entire array if no axis is specified.
* Always returns the mean value(s).
>> np.average()
* Computes the weighted average of an array.
* Supports weights to compute a weighted mean.
* a, weights, axis, returned.
* Averages all elements with optional weighting. If weights is None, it behaves like np.mean().
* Can optionally return the sum of weights along with the weighted mean if returned=True.
>> Key Differences
i) Weighted Average Support:
* np.mean(): Calculates the simple arithmetic mean and does not accept weights.
* np.average(): Can calculate a weighted mean if a weights parameter is provided. If no weights are provided, it defaults to the arithmetic mean, just like np.mean().
ii) Flexibility with Return Values:
* np.average() has an additional parameter returned that, when set to True, returns a tuple containing both the weighted average and the sum of the weights.
iii) Function Signature and Parameters:
* np.mean() is simpler and focuses solely on calculating the arithmetic mean.
* np.average() provides additional functionality for handling weights, making it more versatile in specific use cases where weighted averages are needed.
>> When to Use Each Function
i)Use np.mean() when:
* You need to compute the simple arithmetic mean of an array or matrix.
* Weights are not involved in your calculation.
ii) Use np.average() when:
* You need to compute a weighted average.
* You want to obtain both the weighted mean and the sum of the weights in one call (using the returned=True parameter).
'''
# np.mean() Example:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)  # Simple mean
print(mean_value)  # Output: 3.0
# np.average() Example with Weights:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])  # Higher weight for larger numbers
weighted_average = np.average(data, weights=weights)
print(weighted_average)  # Output: 3.666...

# Conclusion:
# Use np.mean() for a straightforward average.
# Use np.average() when you need to account for different weights in your calculation.

# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# Reversing a NumPy array can be achieved using slicing and the np.flip() function. These methods allow you to reverse the elements along different axes for 1D, 2D, or higher-dimensional arrays.
#...Methods for Reversing a NumPy Array
#i) Using Slicing ([::-1]): This is a simple and efficient way to reverse an array along a specific axis. The syntax [::-1] means "take all elements in reverse order."
#ii) Using np.flip(): This function reverses the order of elements along a specified axis or axes. It is more flexible than slicing as it can handle multi-dimensional arrays and multiple axes.

# Examples for 1D and 2D Arrays
#1. Reversing a 1D Array
#Method 1: Using Slicing

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

# Method 2: Using np.flip()
 
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)  # Output: [5 4 3 2 1]

#2. Reversing a 2D Array
#Consider a 2D array:
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

#Method 1: Using Slicing
#Reverse along rows (axis 0):
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# Reverse along columns (axis 1):
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# Method 2: Using np.flip()
# Reverse along rows (axis 0):
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

#Reverse along columns (axis 1):
reversed_columns = np.flip(arr_2d, axis=1)
print(reversed_columns)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

#Reverse along both axes (rows and columns):
reversed_both = np.flip(arr_2d)
print(reversed_both)
# Output:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

# Conclusion
# Slicing ([::-1]) is a straightforward method for reversing arrays along a single axis.
# np.flip() is more versatile, allowing for reversing along multiple axes or higher-dimensional arrays.

# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
# To determine the data type of elements in a NumPy array, you can use the dtype attribute. This attribute returns the data type object representing the type of elements in the array, such as int, float, bool, or more specific types like int32, float64, etc.
# Determining the Data Type of Elements in a NumPy Array
# Using the dtype Attribute:

import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64 (or int32, depending on the platform)

# Using the type() Function for Specific Elements:
# To get the type of a specific element in the array, you can use the type() function.

print(type(arr[0]))  # Output: <class 'numpy.int64'>
'''
Importance of Data Types in Memory Management and Performance
Memory Management:

Efficient Memory Usage: Different data types in NumPy require different amounts of memory. For example, an int8 type requires 1 byte per element, whereas an int64 type requires 8 bytes per element. Choosing the appropriate data type based on the range of your data can significantly reduce memory usage.
Fixed Size: NumPy arrays have elements of a fixed size (determined by the data type), which allows for efficient memory allocation and compact storage compared to Python lists, which are more dynamic and require additional memory for pointers and type information.
Performance:

Faster Computations: NumPy is implemented in C, and it uses contiguous memory blocks. Operations on arrays of a specific data type (e.g., int32 or float64) are highly optimized and can take advantage of low-level machine instructions, making them faster than operations on Python lists.
Avoiding Type Conversion Overheads: When performing operations on NumPy arrays, choosing the correct data type can avoid unnecessary type conversions that slow down computation. For example, adding two int32 arrays is faster than adding an int32 array to a float64 array, which would require converting the int32 values to float64 first.
Data Type Compatibility:

Precision and Range Control: Certain applications require control over the precision and range of data. For example, float32 may be sufficient for some scientific calculations where memory efficiency is critical, while float64 might be needed for high-precision computations.
Interoperability: Many other libraries (e.g., pandas, TensorFlow) use NumPy arrays as their underlying data structure. Specifying a consistent data type ensures compatibility and avoids errors due to unexpected data type mismatches.
Conclusion
Understanding and managing data types in NumPy is crucial for optimizing memory usage and enhancing performance. Choosing the right data type can lead to significant memory savings and faster computations, especially for large datasets.
'''

# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
'''
>> An ndarray (n-dimensional array) in NumPy is a powerful, multidimensional container for elements of the same data type. It is optimized for numerical computations and scientific data analysis.
i) Key Features of ndarray
* Homogeneous: All elements have the same data type, ensuring efficient operations.
* Multidimensional: Supports multiple dimensions (1D, 2D, 3D, etc.).
* Fixed Size: Size is fixed at creation but can be reshaped.
* Memory Efficient: Uses contiguous memory blocks, minimizing overhead and enhancing speed.
* Element-wise Operations: Supports fast, vectorized operations without explicit loops.
* Broadcasting: Allows operations on arrays of different shapes.
* Advanced Slicing/Indexing: Provides powerful ways to access and manipulate subsets.

>> Differences from Python Lists

ndarray:-
- Homogeneous
- High Memory Efficiency
- Faster for numerical operations
- Direct support

Python List-
- Heterogeneous
- Low memory Efficiency
- Slower for numerical operations
- Nested lists required
Examples
* Creating an ndarray:
'''
import numpy as np
arr = np.array([1, 2, 3])  # 1D array

#* Performing Operations:
result = arr + 10  # Output: [11 12 13]

# Conclusion
# ndarray is highly optimized for numerical computations, offering superior performance and efficiency compared to standard Python lists.

# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
'''
>> NumPy arrays offer significant performance benefits over Python lists, especially for large-scale numerical operations. This advantage comes from NumPy's design and implementation, which are optimized for numerical computing.
* Performance Benefits of NumPy Arrays Over Python Lists
i) Memory Efficiency:
>> Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, unlike Python lists, which are collections of pointers to objects. This contiguity improves memory access patterns and reduces memory overhead.
>> Fixed Data Type: NumPy arrays have a fixed data type (dtype) for all elements, which makes them more memory-efficient. In contrast, Python lists can store elements of different types, requiring extra memory for type information.
ii) Speed and Computation Efficiency:
>> Vectorization: NumPy supports vectorized operations, meaning computations can be performed on entire arrays without writing explicit loops. This reduces the overhead of loop execution in Python and leverages optimized C-level implementations, resulting in much faster execution.
>> Use of Optimized C Libraries: NumPy is implemented in C, allowing it to utilize highly optimized libraries (like BLAS and LAPACK) for numerical computations, making it much faster than Python's built-in loops and functions.
iii) Broadcasting:
>> NumPy's broadcasting mechanism allows operations between arrays of different shapes and sizes without creating unnecessary copies. This reduces both memory usage and computation time.
iv) Efficient Slicing and Indexing:
>> NumPy arrays support advanced slicing, indexing, and masking, allowing efficient data access and manipulation. In contrast, Python lists require manual iteration for such operations, which is slower.
v) Pre-Compiled Functions:
>> NumPy provides a rich set of pre-compiled mathematical functions optimized for array operations, avoiding the overhead of interpreting Python code.
** Performance Comparison Example
>> Here's an example that demonstrates the speed difference between NumPy arrays and Python lists for a large-scale operation:
'''
import numpy as np
import time

# Large size
size = 10_000_000

# Python list
list1 = list(range(size))
list2 = list(range(size))

# NumPy array
array1 = np.arange(size)
array2 = np.arange(size)

# Time for Python list
start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
print("Python list time:", time.time() - start_time)

# Time for NumPy array
start_time = time.time()
result_array = array1 + array2
print("NumPy array time:", time.time() - start_time)
'''
Expected Output
Python list time: Much slower due to interpreted loops and dynamic typing.
NumPy array time: Significantly faster due to optimized C-compiled operations and memory efficiency.
Conclusion
NumPy arrays offer substantial performance benefits over Python lists for large-scale numerical operations due to memory efficiency, vectorization, optimized libraries, and advanced data manipulation capabilities. These advantages make NumPy the preferred choice for scientific computing and data analysis tasks.
'''

# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
'''
>. The vstack() and hstack() functions in NumPy are used to stack or concatenate arrays vertically (along rows) and horizontally (along columns), respectively. They are useful for combining arrays of compatible shapes.
>> Comparison: vstack() vs. hstack()
i) vstack()
* Stacks arrays vertically, i.e., row-wise.
* Stacking Direction Vertical (along rows)
* Arrays must have the same number of columns (same second dimension)

ii) hstack()
* Stacks arrays horizontally, i.e., column-wise.
* Stacking Direction Horizontal (along columns)
* Arrays must have the same number of rows (same first dimension)
Examples Demonstrating Usage
1. vstack() Function
>> The vstack() function stacks arrays vertically, creating a new array by appending rows of one array below another.
'''
import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stacking of 1D arrays
result_vstack_1d = np.vstack((arr1, arr2))
print(result_vstack_1d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Creating two 2D arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

# Vertical stacking of 2D arrays
result_vstack_2d = np.vstack((arr3, arr4))
print(result_vstack_2d)
# Output:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

# 2. hstack() Function
# >> The hstack() function stacks arrays horizontally, creating a new array by appending columns of one array next to another.

import numpy as np

# Creating two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontal stacking of 1D arrays
result_hstack_1d = np.hstack((arr1, arr2))
print(result_hstack_1d)
# Output:
# [1 2 3 4 5 6]

# Creating two 2D arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8, 9], [10, 11, 12]])

# Horizontal stacking of 2D arrays
result_hstack_2d = np.hstack((arr3, arr4))
print(result_hstack_2d)
# Output:
# [[ 1  2  3  7  8  9]
#  [ 4  5  6 10 11 12]]

# Key Points to Remember
# vstack() adds arrays row-wise, requiring them to have the same number of columns.
# hstack() adds arrays column-wise, requiring them to have the same number of rows.
# These functions are helpful when you want to merge or extend arrays in a specific direction.

# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
#The fliplr() and flipud() methods in NumPy are used to flip arrays along specific axes. They provide a convenient way to reverse the order of elements in an array along the horizontal or vertical axis.
# Differences Between fliplr() and flipud()
# i) fliplr()
#* Flips the array left to right (horizontally).
#* Affects the columns (2nd axis)
#* Reverses the order of columns; does not change the number of rows or columns.
# ii) flipud() 
# * Flips the array upside down (vertically).
# * Affects the rows (1st axis)
# * Reverses the order of rows; does not change the number of rows or columns.
'''
Detailed Explanation of Each Method
i) fliplr() (Flip Left to Right):
* Purpose: Reverses the order of columns of a 2D array or a higher-dimensional array along the second axis.
* Usage: It is used to flip the elements in the array from left to right (horizontally).
* Array Requirements: The array must have at least 2 dimensions
'''
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the array horizontally (left to right)
result_fliplr = np.fliplr(arr)
print(result_fliplr)
# Output:
# [[3 2 1]
#  [6 5 4]
#  [9 8 7]]

# ii) flipud() (Flip Up to Down):
#* Purpose: Reverses the order of rows of a 2D array or a higher-dimensional array along the first axis.
#* Usage: It is used to flip the elements in the array from top to bottom (vertically).
#* Array Requirements: The array must have at least 1 dimension.
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flipping the array vertically (upside down)
result_flipud = np.flipud(arr)
print(result_flipud)
# Output:
# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]
'''
Effects on Various Array Dimensions
1D Arrays:

fliplr() is not applicable to 1D arrays because it requires at least 2 dimensions.
flipud() reverses the elements of a 1D array, similar to using np.flip().
2D Arrays:

fliplr() reverses the order of columns (flips the array horizontally).
flipud() reverses the order of rows (flips the array vertically).
Higher-Dimensional Arrays:

fliplr() affects only the last axis (i.e., reverses the columns in the last two dimensions).
flipud() affects the first axis (i.e., reverses the rows in the first two dimensions).
Conclusion
Use fliplr() when you need to reverse the order of columns (horizontal flip).
Use flipud() when you need to reverse the order of rows (vertical flip).
Both methods are useful for manipulating array orientations and can be applied to arrays with two or more dimensions.
'''
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
'''
>> The array_split() method in NumPy divides an array into multiple sub-arrays along a specified axis.
*) Functionality
* Syntax: numpy.array_split(ary, indices_or_sections, axis=0)
* ary: Array to split.
* indices_or_sections:
* Integer: Number of equal-sized sub-arrays. Uneven splits result in the last sub-array being smaller.
* List of Indices: Specific points to split the array. Results in sub-arrays of varying sizes.
Examples
1.Splitting with an Integer:
'''
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sub_arrays = np.array_split(arr, 4)
print(sub_arrays)
# Output: [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

# 2.Splitting with Indices:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sub_arrays = np.array_split(arr, [3, 5, 7])
print(sub_arrays)
# Output: [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

# Handling Uneven Splits
# Integer: Divides array into approximately equal parts; last part may be smaller.
# Indices: Splits exactly at specified points, resulting in varying sizes.
# array_split() ensures arrays are split into sub-arrays as evenly as possible or according to specified indices.

# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

# Vectorization
# Vectorization in NumPy refers to the practice of performing operations on entire arrays at once, rather than using explicit loops. This is achieved through element-wise operations, where operations are applied to each element of the array simultaneously.

# Key Points:

# Efficiency: Vectorized operations are executed at C speed due to NumPy’s underlying implementation, which avoids the overhead of Python loops.
# Conciseness: Vectorization leads to cleaner, more readable code compared to manual loops.
import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
result = a + b
print(result)  # Output: [5 7 9]
'''
Broadcasting
Broadcasting allows NumPy to perform operations on arrays of different shapes. It automatically expands the dimensions of the smaller array to match the larger array, so operations can be performed without explicitly replicating the smaller array.

Key Points:
Automatic Expansion: Smaller arrays are "broadcast" across larger arrays to make their shapes compatible.
Efficiency: Avoids unnecessary memory usage by not copying data but instead using a conceptually expanded view.

Rules for Broadcasting:
If the arrays have a different number of dimensions, prepend the shape of the smaller array with ones until they have the same number of dimensions.
Arrays are compatible if, in each dimension, the sizes are either the same or one of them is 1.
'''
import numpy as np

# Create a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

# Broadcasting adds the 1D array `b` to each row of the 2D array `a`
result = a + b
print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]
'''
