In [ ]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
'''
To create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns, you can follow these steps:
   1) Create the Array: Use numpy.random.randint() to generate the random integers.
   2) Interchange Rows and Columns: Use the .T attribute to transpose the array, which swaps rows with columns.
'''
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Step 2: Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)
 
# Example Output
Original Array:
[[ 7 24 16]
 [89 63 51]
 [19 92 85]]

Transposed Array:
[[ 7 89 19]
 [24 63 92]
 [16 51 85]]
# np.random.randint(1, 101, size=(3, 3)) generates a 3x3 array with random integers from 1 to 100.
# array.T transposes the array, interchanging its rows and columns.

# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
'''
To generate a 1D NumPy array with 10 elements and then reshape it into a 2x5 array and subsequently into a 5x2 array, you can follow these steps:

Generate the 1D Array: Use numpy.arange() or numpy.random.randint() to create the array.
Reshape the Array: Use the .reshape() method to change its shape.
'''
import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)  # or np.random.randint(1, 100, size=10)
print("Original 1D Array:")
print(array_1d)

# Step 2: Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Step 3: Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)

# Example Output
Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

# Explanation
# np.arange(10) generates a 1D array with integers from 0 to 9.
# .reshape(2, 5) reshapes the array into a 2x5 matrix.
# .reshape(5, 2) reshapes the array into a 5x2 matrix.

# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Step 2: Add a border of zeros around the array to create a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:")
print(array_6x6)

#Example Output
Original 4x4 Array:
[[0.234 0.576 0.897 0.123]
 [0.456 0.789 0.234 0.345]
 [0.678 0.912 0.345 0.456]
 [0.789 0.123 0.456 0.678]]

6x6 Array with Zero Border:
[[0.   0.   0.   0.   0.   0.  ]
 [0.   0.234 0.576 0.897 0.123 0.  ]
 [0.   0.456 0.789 0.234 0.345 0.  ]
 [0.   0.678 0.912 0.345 0.456 0.  ]
 [0.   0.789 0.123 0.456 0.678 0.  ]
 [0.   0.   0.   0.   0.   0.  ]]

# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print(array)

#Example Output
[10 15 20 25 30 35 40 45 50 55 60]

#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

# Print the results
print("Original Array:")
print(array)

print("\nUppercase:")
print(uppercase_array)

print("\nLowercase:")
print(lowercase_array)

print("\nTitle Case:")
print(titlecase_array)

print("\nCapitalize:")
print(capitalize_array)

# Example Output
Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize:
['Python' 'Numpy' 'Pandas']

# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np

# Create a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Print the result
print("Original Array:")
print(words_array)

print("\nArray with Spaces Between Characters:")
print(spaced_words_array)

#Example Output
Original Array:
['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']

# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Step 2: Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

#Example Output
Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]

#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

# Example Output
5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]

#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)
print("Random Array:")
print(random_array)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
primes = [num for num in random_array if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(primes)

# Example Output
Random Array:
[  3 120  23  45 678  97 834  16 241 345  51  62 357  89 1000  22 678
  13  57 432  89  43  55 234 678  88  23 467 908  77 124  89 923  50
  19  29  33  77  89  41  56  19  67  21 104 500  83 670  92  37  45
  51 121  73  29  84 900  12  63  73  79  89  99 145  23  55 234 453
  97  88  33  21  29 456  68  77  34  57]

Prime Numbers in the Array:
[3, 23, 97, 13, 89, 43, 23, 467, 89, 19, 29, 89, 41, 19, 67, 83, 73, 29, 79, 89, 97, 29]

#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.